[package]
name = "crunchyroll-rs"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Pure Rust implementation of the crunchyroll api."
documentation = "https://docs.rs/crunchyroll-rs"
readme = "README.md"
repository.workspace = true
license.workspace = true
keywords = ["anime", "crunchyroll", "downloader"]
categories = ["api-bindings"]
include = ["/Cargo.toml", "/LICENSE-APACHE", "/LICENSE-MIT", "/README.md", "/src/**", "/tests/**"]

[package.metadata.docs.rs]
rustdoc-args = ["--cfg", "docsrs"]
all-features = true

[workspace]
members = [".", "examples/*", "internal"]

[workspace.package]
# increase version of 'crunchyroll-rs-internal' dependency when updating
version = "0.18.5"
authors = ["Crunchy Labs Maintainers"]
edition = "2024"
rust-version = "1.88.0"
repository = "https://github.com/crunchy-labs/crunchyroll-rs"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
anyhow = "1.0"
byteorder = "1.5"
chrono = { version = ">=0.4.35", features = ["serde"] }
dash-mpd = { version = "0.20", default-features = false }
# increase version of 'crunchyroll-rs-internal' dependency when updating
crunchyroll-rs-internal = { path = "internal", version = "0.18.5" }
darling = "0.24"
futures-util = { version = "0.3", default-features = false, features = ["std"] }
gtk = "0.18"
http = "1.5"
jsonwebtoken = { version = "11.0", default-features = false, features = ["rust_crypto"] }
proc-macro2 = "1.0"
# the patch version number is necessary for the 'reqwest' and 'rustls' dependencies to prevent incompatability errors
# (https://github.com/seanmonstar/reqwest/issues/1837)
reqwest = { version = "0.13.5", features = ["cookies", "json", "multipart", "query", "rustls"] }
rand = "0.10"
quote = "1.0"
regex = { version = "1.13", default-features = false, features = ["std"] }
rustls = { version = "0.23.4", default-features = false, features = ["ring", "std", "tls12"] }
scraper = "0.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
serde_urlencoded = "0.7"
smart-default = "0.7"
syn = { version = "3.0", features = ["full"] }
tao = "0.35"
tokio = { version = "1.53", features = ["sync"] }
tower-service = "0.3"
uuid = { version = "1.24", features = ["v4"] }
webpki-roots = "1.0"
wry = "0.55"

[dependencies]
byteorder = { workspace = true }
chrono = { workspace = true }
dash-mpd = { workspace = true }
futures-util = { workspace = true }
http = { workspace = true }
jsonwebtoken = { workspace = true }
reqwest = { workspace = true }
rustls = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_urlencoded = { workspace = true }
smart-default = { workspace = true }
tokio = { workspace = true }
uuid = { workspace = true }
webpki-roots = { workspace = true }

crunchyroll-rs-internal = { workspace = true }

regex = { workspace = true, optional = true }
scraper = { workspace = true, optional = true }
tower-service = { workspace = true, optional = true }

[dev-dependencies]
anyhow = { workspace = true }
rand = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }

[features]
default = ["parse"]

# Add various stabilizations as Crunchyroll delivers wrong api results in some cases.
experimental-stabilizations = []
# Add the ability to specify (tower based) custom middleware services.
middleware = ["dep:tower-service"]
# Add functionality to parse Crunchyroll urls.
parse = ["dep:regex"]
# Add functionality to get the release calendar.
release-calendar = ["dep:scraper", "parse"]

# Internal! Do not use it outside of testing
__test = []
__test_strict = []
