[package]
name = "sso-login"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crunchyroll-rs = { path = "../.." }

http = { workspace = true }
reqwest = { workspace = true }
tao = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
uuid = { workspace = true }
wry = { workspace = true }

[target.'cfg(unix)'.dependencies]
gtk = { workspace = true }
