[package]
name = "middleware"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
crunchyroll-rs = { path = "../..", features = ["middleware"] }
reqwest = { workspace = true }
serde_json = { workspace = true }
tower-service = { workspace = true }
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
