[package]
name = "crunchyroll-rs-internal"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
description = "Internal crate for crunchyroll-rs. Do not use directly."
repository.workspace = true
license.workspace = true
include = ["/Cargo.toml", "/LICENSE-APACHE", "/LICENSE-MIT", "/src/**"]

[lib]
proc-macro = true

[dependencies]
darling = "0.24"
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "3.0", features = ["full"] }
