name: update-credentials

on:
  schedule:
    - cron: '0 0 1,15 * *'
  workflow_dispatch:

jobs:
  update-credentials:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install jadx
        run: |
          JADX_VERSION=$(curl "https://api.github.com/repos/skylot/jadx/releases/latest" | grep -Po '"tag_name": "v\K[0-9.]+')
          
          curl -L -o jadx.zip "https://github.com/skylot/jadx/releases/download/v$JADX_VERSION/jadx-$JADX_VERSION.zip"
          unzip jadx.zip -d jadx
          chmod +x "$(pwd)/jadx/bin/jadx"
          
          echo "$(pwd)/jadx/bin" >> $GITHUB_PATH

      - name: Update credentials
        id: update
        run: bash .github/scripts/update_credentials.sh

      - name: Create pull request
        if: steps.update.outputs.changed == 'true'
        uses: peter-evans/create-pull-request@v7
        with:
          add-paths: |
            src/crunchyroll.rs
            examples/sso-login/src/main.rs
          commit-message: "[update-credentials action] Update auth credentials & user-agent"
          title: "Update auth credentials & user-agent"
          body: |
            Update the auth credentials & user-agent to match the latest android tv & phone apk
          base: master
          branch: update-auth-${{ steps.update.outputs.tv_vername }}_${{ steps.update.outputs.phone_vername }}
